version: '3'
services:
  node:
    environment:
      NODE_ENV: development
      DEBUG: "express:*"
    command:
    - /bin/sh
    - -c
    - |
      npm install
      npm run prestart
      npm run start:debug
